'use strict';

/**
 * Paths proxied to Unbounce
 */
module.exports = [
  // /^\/prx-sponsorship(\/|$)/,
  // /^\/smithsonian-shows(\/|$)/,
  // /^\/inflection-point(\/|$)/,
  // /^\/que-pasa-midwest(\/|$)/,
  // /^\/out-of-the-blocks(\/|$)/,
  // /^\/versify(\/|$)/,
  // /^\/us-them(\/|$)/,
  // /^\/we-live-here(\/|$)/,
  // /^\/west-wing-weekly(\/|$)/,
  // /^\/ear-hustle(\/|$)/,
  // /^\/the-memory-palace(\/|$)/,
  // /^\/memory-palace(\/|$)/,
  // /^\/milk-street-radio(\/|$)/,
  // /^\/this-is-love(\/|$)/,
  // /^\/trump-con-law(\/|$)/,
  // /^\/theory-of-everything(\/|$)/,
  // /^\/kitchen-sisters(\/|$)/,
  // /^\/the-truth(\/|$)/,
  // /^\/the-truth-v2(\/|$)/,
  // /^\/radio-diaries(\/|$)/,
  // /^\/loveradio(\/|$)/,
  // /^\/criminal-show(\/|$)/,
  // /^\/the-bugle(\/|$)/,
  // /^\/allusionist(\/|$)/,
  // /^\/mortified(\/|$)/,
  // /^\/song-exploder(\/|$)/,
  // /^\/99-invisible(\/|$)/,
  // /^\/radiotopia(\/|$)/,
  // /^\/esquire-classic(\/|$)/,
  // /^\/reveal(\/|$)/,
  // /^\/outside-magazine(\/|$)/,
  // /^\/outside-podcast(\/|$)/,
  // /^\/outside-pod(\/|$)/,
  // /^\/htba(\/|$)/,
  // /^\/hermoney(\/|$)/,
  // /^\/orbital-path(\/|$)/,
  // /^\/fugitive-waves(\/|$)/,
  // /^\/podcast-garage-audiobook(\/|$)/,
  // /^\/podcast-garage-voiceover(\/|$)/,
  // /^\/podcast-garage(\/|$)/,
  // /^\/library-stories(\/|$)/
];
